App\Entity\ScientificJob:
  attributes:
    order:
      id: "DESC"
  collectionOperations:
    get:
      normalization_context:
        groups: ['ScientificJob:collection']
    post:
      denormalization_context:
        groups: ['ScientificJob:write']
  itemOperations:
    get:
      normalization_context:
        groups: ['ScientificJob:item']
