App\Entity\University:
  attributes:
    order:
      id: "DESC"
  collectionOperations:
    get:
      normalization_context:
        groups: ['University:collection']
    post:
      denormalization_context:
        groups: ['University:write']
  itemOperations:
    get:
      normalization_context:
        groups: ['University:item']
