# Domain related mapping
App\Entity\User:
  attributes:
    id:
      groups:
        - 'User:item'
        - 'User:collection'
        - 'ScientificJob:collection'
        - 'ScientificProject:item'
        - 'ScientificProject:collection'
    displayName:
      groups:
        - 'User:item'
        - 'User:collection'
        - 'ScientificJob:collection'
        - 'ScientificProject:item'
        - 'ScientificProject:collection'
    university:
      groups:
        - 'User:item'
        - 'User:collection'
        - 'ScientificJob:collection'
        - 'ScientificProject:item'
        - 'ScientificProject:collection'
    contacts:
      groups:
        - 'User:item'
        - 'User:collection'
        - 'ScientificProject:item'
    hardSkills:
      groups:
        - 'User:item'
        - 'User:collection'
        - 'ScientificProject:item'
    profileByBelbin:
      groups:
        - 'User:item'
        - 'User:collection'
    scientificJobsTotal:
      groups:
        - 'ScientificProject:item'

App\Entity\UserContact:
  attributes:
    phone:
      groups:
        - 'User:item'
        - 'User:collection'
        - 'ScientificProject:item'
    email:
      groups:
        - 'User:item'
        - 'User:collection'
        - 'ScientificProject:item'
    vk:
      groups:
        - 'User:item'
        - 'User:collection'
        - 'ScientificProject:item'
    facebook:
      groups:
        - 'User:item'
        - 'User:collection'
        - 'ScientificProject:item'

App\Entity\UserBelbinProfile:
  attributes:
    coordinator:
      groups:
        - 'User:item'
        - 'User:collection'
    shaper:
      groups:
        - 'User:item'
        - 'User:collection'
    teamWorker:
      groups:
        - 'User:item'
        - 'User:collection'
    resourceInvestigator:
      groups:
        - 'User:item'
        - 'User:collection'
    plant:
      groups:
        - 'User:item'
        - 'User:collection'
    monitorEvaluator:
      groups:
        - 'User:item'
        - 'User:collection'
    implementer:
      groups:
        - 'User:item'
        - 'User:collection'
    specialist:
      groups:
        - 'User:item'
        - 'User:collection'
    completerFinisher:
      groups:
        - 'User:item'
        - 'User:collection'
